---
language: ruby
sudo: false
cache: bundler
rvm:
- 2.4.2
script: bundle exec rake $TASK
after_success: bundle exec jekyll algolia push
env:
- TASK='jekyll:check'
- TASK='jekyll:check_external_links'
matrix:
  fast_finish: true
  allow_failures:
  - env: TASK='jekyll:check_external_links'
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
