permalink: /about/news/:year/:month/:day/:title.html
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "blog_post"
