permalink: /about/news/:year/:month/:day/:title.html
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "blog_post"
  -
    scope:
      path: "events"
      type: "pages"
    values:
      layout: "events"
      group: "events"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      group: "events"
collections:
  events:
    output: true
maps_api_key: AIzaSyCtjkfaB7Q7Qf2Fy11YrtNn9gZFKeGtUwM